services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - ../klikdat_db:/var/lib/postgresql/data
    env_file:
      - .env.dev

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  django-web:
    build: .
    container_name: django-docker
    environment:
      - DJANGO_DEBUG
    ports:
      - "1337:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
